excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://iraghumitra.github.io
title: Angular2
email: raghumitra.ksv@gmail.com
author: RaghuMitra
description: Angular 2
paginate: 3
google_analytics: 
